# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SmallPrimaryExchange(str, Enum):
    """
    Primary exchanges that can be mapped to Vividseats.
    """

    """
    allowed enum values
    """
    MPV = 'MPV'
    MILB = 'MILB'
    MLB = 'MLB'
    PLAYHOUSESQUARE = 'Playhousesquare'
    STRAZ = 'Straz'
    TELECHARGE = 'Telecharge'
    PACIOLAN = 'Paciolan'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SmallPrimaryExchange from a JSON string"""
        return cls(json.loads(json_str))


